### ISSUE TITLE
nothing kills forever scripts?

### ISSUE THREAD

**Issue by niconicosette** [foreverjs/forever#1007]
i've been using forever for a few weeks and it was fine at first but, the last 2 days i've encountered a problem where literally nothing will stop the scripts. even deleting the scripts and uninstalling forever didn't stop them and the only reason i managed to stop them was because i could regenerate the tokens needed in the scripts. what's more concerning is that `forever list` doesn't display processes that are still running after attempts to kill them have failed.

**Comment by newradius** [comment]
Have you started the scripts with a different user maybe root?

**Comment by niconicosette** [comment]
it was the same user.

**Comment by newradius** [comment]
Have you tried PM2 instead of forever?
