### ISSUE TITLE
Security scan detect utile as low level vulnerability WS-2018-0148

### ISSUE THREAD

**Issue by jpgcode** [foreverjs/forever#1021]
`utile` allocates uninitialized Buffers when number is passed in input.
Before version 0.3.0

Forever is still using `utile` 0.2.1.

Can we look for upgrade?

**Comment by kibertoad** [comment]
Sure!

**Comment by kibertoad** [comment]
Could you please test latest version from master?

**Comment by jpgcode** [comment]
It looks great, are we planning to release to NPM repo soon? Do not want to rely on master in PROD for long time.

**Comment by kibertoad** [comment]
@indexzero Are we :)?

**Comment by kibertoad** [comment]
New version with a fix is finally out! Sorry for the delay.
