### ISSUE TITLE
.foreverignore file not working for sub directories with -w

### ISSUE THREAD

**Issue by moneal** [foreverjs/forever#235]
Normal ignore rules don't seem to work correctly with forever. I was trying to add my .git folder and was unable to get it working. I tried with the below file.

    .git
    .git/
    .git/*

The first line is the only one that should be needed.

If you did a git pull and a file changed in the .git folder forever would restart. 

    info:   restaring script because /mnt/home/test/.git/FETCH_HEAD changed
    warn: Forever detected script exited with code: null
    warn: Forever restarting script for 1 time

**Comment by kevzettler** [comment]
If this is not going to be fixed at least remove it. Update the documentation and point people to forever monitor if thats the preferred solution.

**Comment by indexzero** [comment]
@kevzettler it will be fixed when there is time. I was able to do a quick spike on this tonight by adding a test case to `forever-monitor` in https://github.com/foreverjs/forever-monitor/commit/3af5ce7b1d868378b48ed67129243de814cdc79e. This is _not_ a `minimatch` issue since `minimatch` works fine in `forever-monitor. We must somehow be passing bad config information to the `forever-monitor` instance.

If you'd like to contribute some time of your own it would be very welcome.

**Comment by dermidgen** [comment]
@indexzero - I don't see what is still borked here. Let's close this.

https://github.com/foreverjs/forever/issues/235#issuecomment-23847009 - as well as https://github.com/foreverjs/forever-monitor/pull/30 which you already merged into forever-monitor ages ago appear to have resolved the issues.

See also https://github.com/foreverjs/forever/issues/235#issuecomment-47238099
All those +1 folks are mistaken and not paying attention. PR30 was merged in 2013.

**Comment by indexzero** [comment]
Thanks @dermidgen. I'm going to leave this open until I have test coverage for it in `forever`, but I appreciate your time looking into this.

**Comment by dermidgen** [comment]
Roger that. I will happily join you in this effort. I see you've started with some test coverage in ```forever-monitor```; I will start looking at ```forever```

**Comment by indexzero** [comment]
Closing this in favor of tracking it on #738.

**Comment by daslicht** [comment]
Is there meanwhile any solution ?

**Comment by jeffmcmahan** [comment]
I love forever, and have used the CLI for many years in many projects. The developers deserve enormous credit.

Now, I'm using v0.15.3 and in my case, ignored subdirectories are being watched. This has been so for years, and I've come back to this thread a half dozen times over the past 4-5 years. 

I think the following sums up the situation: (i) The maintainers seemed to regard the problem with the CLI as fixed before it worked the way the users above wanted. (ii) There's no test in place that covers the way the users above want the CLI to work.

The following demonstrates the the CLI does not respect `.foreverignore` subdirectories, exactly as OP described (paste into terminal):

```sh
# Create a project directory.
cd ~ && mkdir foo-project

# Create project files.
echo "require('http').createServer(r => {}).listen(3000)" > foo-project/index.js
mkdir foo-project/foo
mkdir foo-project/foo/bar
echo "console.log('fizz');" > foo-project/foo/bar/index.js

# Add .foreverignore to tell forever to ignore foo.
echo "foo" > foo-project/.foreverignore

# Add a JSON conf file to tell forever to watch the project.
echo "{\"watch\":true,\"script\":\"index.js\"}" > foo-project/forever-conf.json

# Run the project.
cd foo-project && forever start forever-conf.json
```

`$ forever list` will show a running process. Now we'll change a file that lives in `foo/bar` (paste into terminal):

```sh
cd ../
echo "console.log('buzz');" >> foo-project/foo/bar/index.js
```

The process should not have restarted, but the log file will indicate that it did so:

```
error: restarting script because add changed
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #1
```

If I'm doing something wrong here, *please* indicate how I should change what I'm doing; I'll be grateful.

**Comment by wyqydsyq** [comment]
@jeffmcmahan the solution is to use PM2 or nodemon. Forever hasn't had any commits to master in over 2 years, it seems quite clear it's a dead project.

Nodemon is almost identical to forever in features, except their [watch/ignore actually works as documented](https://github.com/remy/nodemon#ignoring-files).

**Comment by jeffmcmahan** [comment]
Not sure how I failed to notice that. Thanks.
