### ISSUE TITLE
Spawning applications based on a directory of config files

### ISSUE THREAD

**Issue by mattrobenolt** [foreverjs/forever#260]
Proposing this would allow a more traditional deployment method with a "sites-available".

I envision a command such as `forever vhosts /etc/forever/sites-available` and the directory would contain a set of *.json config files.

Each config would be structured similar to:

```javascript
{
  "script": "/var/www/app.js",
  "accessLog": "/var/log/my-app/access.log",
  "errorLog": "/var/log/my-app/access.log",
  "options": {
    "max": 3
  }
}
```

All of these options would be passed along right to a start command, simulating a bunch of `forever start ...` commands.

**Also**: I'm willing to develop the feature myself, I just want to make sure it's done in a way that is in line with the rest of the project.

**Comment by indexzero** [comment]
Fixed in #733 and #737
