### ISSUE TITLE
[bug] -w doesnt restart if node didnt write anything in stdout

### ISSUE THREAD

**Issue by demark** [foreverjs/forever#280]
subj.

if i run server what doesnt write anything to stdout, forever dont restart script until script write smth to stdout.

`app/src$ forever start -e ../err.log -o ../out.log -w -c coffee app.coffee`

files:

```
app/
    src/
        app.coffee
.config
```

`nodejs v0.6.16 forever v0.9.1`

**Comment by indexzero** [comment]
You could please check this again @demark ? We switched to `chokidar` in `forever@0.15.0` (specifically by upgrading to `forever-monitor@1.6.0`) which is much more stable than what was used previously. 

Given the age of this issue I'm going to close it.
