### ISSUE TITLE
empty logs (again)

### ISSUE THREAD

**Issue by EdHubbell** [foreverjs/forever#288]
I saw this looked like it was brought up a few weeks ago, but was resolved.  I'm still seeing an issue.  I'm using Node v0.6.18 and forever@0.9.1.

forever start --append --logFile forever.log --outFile out.log --errFile err.log -c coffee geotweet.coffee

and 

forever start --a -l forever.log -o out.log -e err.log -c coffee geotweet.coffee

Both make an empty out.log and err.log (if they don't already exist).  forever.log seems fine and fills.

My syntax is copied directly from my dev server, where I'm running Node v0.6.12 and forever@0.8.5

Uninstalling and rolling back to forever@0.8.5 and the problem goes away.  I get my nice log files and a good night's sleep besides.  No clue what the last working version for my specific conditions was, but forever@0.8.5 was good enough for my dev box, so into prod it goes.  ~Ed

**Comment by indexzero** [comment]
Closing this due to age of the issue.
