### ISSUE TITLE
Forever restarts even when not using -w option

### ISSUE THREAD

**Issue by conflagrator** [foreverjs/forever#391]
I am starting forever with the following command: 
```bash
sudo forever start -a -l /var/log/node/forever -o /var/log/node/out -e /var/log/node/err server.js
```
Before, the server was started with the -w option, but now, without using the option, the server keeps restarting on file changes in my main directory and the sub-directories. I also deleted my ~/.forever dir, without any results.

**Comment by indexzero** [comment]
You could please check this again @conflagrator? We switched to `chokidar` in `forever@0.15.0` (specifically by upgrading to `forever-monitor@1.6.0`) which is much more stable than what was used previously. 

Given the age of this issue I'm going to close it.
