### ISSUE TITLE
process.cwd() is not sourceDir

### ISSUE THREAD

**Issue by RJacksonm1** [foreverjs/forever#427]
Where test/test.js contains

    console.log(process.cwd());

the following produces "/home/rjackson", where I would expect "/home/rjackson/test"

    cd /home/rjackson
    forever --sourceDir /home/rjackson/test test.js

This is running forever 0.10.8.  Any idea what the problem is?

**Comment by indexzero** [comment]
Fixed via https://github.com/foreverjs/forever-monitor/issues/66
