### ISSUE TITLE
python (non-node) process -o -e -l (logging of forever and child) not working

### ISSUE THREAD

**Issue by m4mum** [foreverjs/forever#442]
raxit@ip-10-128-91-44:/home/raxit/tmp$ pwd
/home/raxit/tmp

raxit@ip-10-128-91-44:/home/raxit/tmp$ cat a.py 
import time
while(1):
	print "Hello"
	time.sleep(1)

raxit@ip-10-128-91-44:/home/raxit/tmp$ forever start -c python a.py -o /home/raxit/tmp/myout.log -e /home/raxit/tmp//myerr.err   -l /home/raxit/tmp/forever.log 
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: a.py

raxit@ip-10-128-91-44:/home/raxit/tmp$ ls -lrt
total 8
drwxrwxr-x 3 raxit raxit 4096 Mar 19 05:47 jsontest
-rw-rw-r-- 1 raxit raxit   53 Jun 30 08:10 a.py

raxit@ip-10-128-91-44:/home/raxit/tmp$

**Comment by markstos** [comment]
`forever` is working as documented. Check out the "usage" line seen when you run `forever --help`:

```
usage: forever [action] [options] SCRIPT [script-options]
```

Your logging options appear *after* your script name. Thus, they are interpreted as options to your script not options to the `forever` action. 

I recommend that this issue be closed.

**Comment by indexzero** [comment]
Duplicate #373.
