### ISSUE TITLE
Forever -w doesn't detect symlinked directory changes

### ISSUE THREAD

**Issue by aMoniker** [foreverjs/forever#444]
I'm mounting a VirtualBox shared folder in a VM, then symlinking a directory within it to `/var/www/mysite`

When I run `forever -w main.js` within `/var/www/mysite` it does not detect changes in order to restart. I can confirm that the files are actually changed, and that the symlink reflects that.

**Comment by indexzero** [comment]
You could please check this again @aMoniker ? We switched to `chokidar` in `forever@0.15.0` (specifically by upgrading to `forever-monitor@1.6.0`) which is much more stable than what was used previously. 

Given the age of this issue I'm going to close it until you can confirm it's still not working. Here's a pretty good boilerplate to use for reproducing: https://gist.github.com/dillonkrug/25ee1397510aa4dec1d7
