### ISSUE TITLE
"watch file changes" feature doesn't work

### ISSUE THREAD

**Issue by mocheng** [foreverjs/forever#462]
I'm using forever v0.10.8. 

The doc tells the command line options as:

   -w, --watch      Watch for file changes
    --watchDirectory Top-level directory to watch from

However, as I type:

sudo forever start app.js -w --watchDirectory "."

After the app.js is launched by forever, I changed some files in folder controller/admin.js. The change doesn't make forever to restart and re-read the  file change.

Anything I did wrong?
What's the proper way to make forever watch file change?

**Comment by k1g7st** [comment]
forever -w --watchDirectory /var/www/project_path start app.js
SUCCESS on centos 7

output log like
error: restarting script because /var/www/project_path/app.js changed
error: Forever detected script exited with code: null
error: Script restart attempt #1

**Comment by anthonye2007** [comment]
`forever -w --watchDirectory=<fullPathToYourDir>  start  <fullPathToFile>`
Works for me on Ubuntu 14

For me, I needed to pass in the full path to the directory and the file.

**Comment by indexzero** [comment]
This has been fixed for some time now.

**Comment by ios122** [comment]
just note and improve, test with OSX and Ubuntu,cd to your project first:

```
forever start  --minUptime $(expr 1000 \* 365 \* 24 \* 60 \* 60 \* 1000)  --spinSleepTime $(expr 1 \* 1000) -w --watchDirectory $(pwd) --watchIgnore *.log  --watchIgnore node_modules index.js
```

**Comment by benderlidze** [comment]
@anthonye2007 Thanks! CentOS6 confirmed as working!
forever -w --watchDirectory=/home/anthony/Deployment/deploy/green-www start /home/anthony/Deployment/deploy/green-www/main.js
