### ISSUE TITLE
feature request : notify when script stop

### ISSUE THREAD

**Issue by m4mum** [foreverjs/forever#474]
Hi

We are using forever and it works great!

Whenever our js file crash, forever restart them, however if it can notify on e-mail as well, it will be great!

Raxit

**Comment by Geoffzable** [comment]
Any update on this?

**Comment by px751** [comment]
+1

**Comment by muzaparoff** [comment]
+

**Comment by indexzero** [comment]
Duplicate of #171.

**Comment by JuliaRakitina** [comment]
+1

**Comment by ThBastos** [comment]
+1
