### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by peek4y** [foreverjs/forever#476]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

This is the error i get in logs, whenever i try to run any script with  FOREVER.

**Comment by indexzero** [comment]
Closing this due to the age of the issue.
