### ISSUE TITLE
Duplicate log entries

### ISSUE THREAD

**Issue by chovy** [foreverjs/forever#499]
Duplicate log entries are happening again --- https://github.com/nodejitsu/forever/issues/212

I still have this problem.

```
forever start -l ~/log/app.log -o ~/log/app.log -e ~/log/app.log -a --sourceDir ~/www/app app.js

$ npm list forever -g
/usr/local/lib
└── forever@0.10.9
```

**Comment by indexzero** [comment]
Duplicate of #373. As a point of process we are now locking all duplicate issues. Please continue the discussion on #373 if you are interested.

**Comment by indexzero** [comment]
FYI I believe this is by design right now since `-l` is the combined log of `-o` and `-e` so you're telling forever to log twice. Regardless we should be smarter about user input that we get for log file names.
