### ISSUE TITLE
restarting script for 0 time

### ISSUE THREAD

**Issue by donpdonp** [foreverjs/forever#510]
I wish i had more details, but forever 'hung' while monitoring a js script. (forever v0.10.8 node 0.8.15)

Log output is:
<pre>
error: Forever detected script exited with code: 1
events.js:71
        throw arguments[1]; // Unhandled 'error' event
error: Forever restarting script for 3 time
</pre>

so far so good but another error happened and
<pre>
events.js:71
        throw arguments[1]; // Unhandled 'error' event
error: Forever detected script exited with code: 1
error: Forever restarting script for 0 time
</pre>

and was never restarted again. there was no limit set for the number of restarts.

**Comment by indexzero** [comment]
Fixed in #632.
