### ISSUE TITLE
Restarting kills forked processes, even if they are detached

### ISSUE THREAD

**Issue by rickihastings** [foreverjs/forever#529]
In node you can spawn processes and detach them so that they keep running when the parent dies, or when the parent restarts. I have a package which does this to keep IRC clients running if their parent processes need to restart.

You can do it by setting the `detached` boolean to `true` in the `child_process.spawn` function and then calling `child.unref()` see: http://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

In a normal use case my process doesn't need to restart any child processes when the main one dies or restarts, however when running it with forever, the children die when the main process is restarted even if it's detached.

I'll try to offer a means to replicate this problem because my current stack is quite large, however the package is at https://github.com/ircanywhere/irc-factory, cloning the repo and running `node examples/persistent.js` will prove that a child process can be disconnected from the main even if it dies (you'll have to go to freenode and /whois the irc client made). But if you run it with `forever start examples/persistent.js` and try a `forever restartall` it'll restart both processes.

This is not really ideal, I'm guessing it's something to do with forever taking a note of the children it's spawned and restarting them aswell, unless there is a setting to avoid this happening?

**Comment by indexzero** [comment]
By default `forever-monitor` has `killTree` set to `true` which will use the `ps-tree` module to kill all child processes spawned by the any process `forever` spawns regardless of the detached state.

You can disable this behavior by running:

```
forever start --no-killTree ./my-script-that-spins-up-detached-child-procs.js
```
