### ISSUE TITLE
`forever list` doesn't see other user's processes, not even with sudo

### ISSUE THREAD

**Issue by dandv** [foreverjs/forever#544]
I have a process launched by user `dandv`, and it shows up under `forever list`.

But if I run `forever list` while logged in as another user, it shows `No forever processes running`. `sudo forever list` shows the same. I've even tried running the command from `/` or from `/home/dandv` - same result.

**Comment by jasonswearingen** [comment]
i had this issue, Here is my resolution.

I am running forever via crontab ```@reboot``` on a non-admin account called ```serviceaccount```

I could not see forever when logging into that non-admin account via ```sudo -u serviceaccount bash```  

but once i used ```su serviceaccount``` I was able to use ```forever list``` no problem

**Comment by Gerst20051** [comment]
:+1:

**Comment by indexzero** [comment]
Duplicate of #415.
