### ISSUE TITLE
Watch an external folder

### ISSUE THREAD

**Issue by Vadorequest** [foreverjs/forever#554]
I'm wondering if that's possible to watch an external folder, because I use a shared folder between two node applications, when a file is changed inside the shared folder, the servers doens't restart.

Any way to achieve that? The three folders are at the same level.

**Comment by indexzero** [comment]
This is possible, but it's a bit hacky. You'd need to make the `--watchDirectory` a parent directory of both of those and place the `.foreverignore` in there with complete paths. So in this setup:

```
my-apps/
  .foreverignore
  shared/
  app1/
  app2/
```

Your `.foreverignore` would then have to have:

```
shared/whatever
shared/something-else-ignored
app1/ignore-this-too
app2/and-ignore-this
```

Then you'd have to start forever as so:

```
cd my-apps
forever start app1/script.js -w --watchDirectory $PWD 
```
