### ISSUE TITLE
forever 0.11.1: error: Forever detected script was killed by signal: null; script not restarted.

### ISSUE THREAD

**Issue by triccardi-systran** [foreverjs/forever#570]
Issue was raised and fixed in #420 but it happens again with forever 0.11.1.

I have a node script that early exits for internal reasons (in less than a second), then this is logged:
"error: Forever detected script was killed by signal: null"
Then the node process exits.
The forever monitor process still exists though.

But forever list still lists the script as running, with the old pid listed, which points to no node process anymore.

forever should have restarted the node script (or marked it as failed).

It may be the anti spin code that doesn't work well though, I haven't tested further yet.

**Comment by indexzero** [comment]
Fixed in #702.
