### ISSUE TITLE
Start several servers from config file

### ISSUE THREAD

**Issue by piranna** [foreverjs/forever#591]
Allow to exec ```forever``` giving as parameter a config file (for example in JSON format, ideally the same one as [ndm](https://github.com/npm/ndm#the-servicejson-file-) or based on it) so several services can be launch at the same time. The purpose of this is to use ```forever``` as daemon manager for [NodeOS](http://node-os.com/) on boot time.

As a bonus, the config file would have an ```enabled``` field to allow to omit the start of a service if it's not set.

**Comment by indexzero** [comment]
Fixed in `0.15.0
