### ISSUE TITLE
Service stop fails, unable to get PID

### ISSUE THREAD

**Issue by HALdtripp** [foreverjs/forever#635]
We recently deployed forever for a node application. When attempting to do a service stop or service restart, the shutdown would fail with.
 
     Shutting down koningsdam: Could not get pid
 
Looking into the init script I found it was failing to get the PID. I was able to remedy this by changing the PID discovery to PID=$(<$PIDFILE) instead of the default  PID=$(forever --plain list…

node was installed from RPM. Forever was installed with npm install forever.

**Comment by scien** [comment]
I just ran into this issue. Fedora23 64-bit, node v5.3.0, forever v0.15.1

`> forever start -c ./path/to/coffee-script SCRIPT`
`> forever stop SCRIPT` 
`error:   Forever cannot find process with id: SCRIPT`

the only way to stop it was to grab the pid from `forever list` and then `forever stop pid`

**Comment by indexzero** [comment]
Closing due to age.
