### ISSUE TITLE
[deprecate] logFile, pidFile, path can not be arbitrarily modified

### ISSUE THREAD

**Issue by Tjatse** [foreverjs/forever#637]
The below options should better be removed, people change `root` by using `forever set root [ROOT]` cmd only.
`-l, -o, -e, -p, --pidFile` will destroy the ecological environment of `forever`, as you known, we manage `pids`/`sock`/`logs` by `forever#load` and get processes from `sock` directory, if people use `-p` to change the `root`, `forever` will go into a quagmire of confusion, 'Cause the previous processes are all persisted in the previous `root`. 

```
-l  LOGFILE     Logs the forever output to LOGFILE
-o  OUTFILE     Logs stdout from child script to OUTFILE
-e  ERRFILE     Logs stderr from child script to ERRFILE
-p  PATH        Base path for all forever related files (pid files, etc.)
-a, --append    Append logs
--pidFile       The pid file
--uid           Process uid, useful as a namespace for processes (must wrap in a string)
                    eg. forever start --uid "production" app.js
                    forever stop production
```
- `-a` should always be true
- `--uid` should be `id`

**Comment by indexzero** [comment]
Closing due to age.
