### ISSUE TITLE
forever doesn't kills the child process every time while inside chroot env

### ISSUE THREAD

**Issue by rah-gupta** [foreverjs/forever#640]
Hi,
The problem is that forever is not always killing the child process which it spawns while inside chroot environment.
My Environment: I'm using forever to start/stop a node.js program which is started in chroot-ed environment. The command used to start is below -

START command:
HOME=/some/path/f-home /usr/sbin/chroot --userspec=userx:userx /opt/chroot /usr/bin/env NODE_ENV=devenv /usr/local/bin/forever -l /some/path/f-home/forever.log -a start /some/path/code/app.js

STOP command:
HOME=/some/path/f-home /usr/sbin/chroot --userspec=userx:userx /opt/chroot /usr/bin/env NODE_ENV=devenv /usr/local/bin/forever -l /some/path/f-home/forever.log -a stop /some/path/code/app.js

The above lines are written inside an init script and it is invoked as "/etc/init.d/app-chroot-script [start | stop]". This is starting the app.js perfectly with monitor process having ppid=1 & pid=200(say) AND the node process with ppid=200(the monitor's pid). The problem arises when it is stopped using command 

Sometimes it stops both monitor & child process but sometimes it doesn't stops the child process. In that case the chilld process assumes ppid of root(root adopts it). This is happening at random times (not predictible). The error in the forever log file looks like below.
__________________________________________________
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

Edit: I'm using 
Node Version : v0.10.24
Forever Version : v0.11.1

**Comment by kaven276** [comment]
I have the problem too.

[static@nodejs pids]$ cat ~/dxt/test/dxtTest.sh
cd ~/dxt/test && java -jar ./dxtAgent.jar

forever start --append --uid "dxtTest" --pidFile dxtTest -p ~/dxt/test/ -c bash ~/dxt/test/dxtTest.sh

forever stop / forever restart will kill .sh script process, but not kill the java process !

**Comment by rah-gupta** [comment]
I found out the solution to this. It seems somehow that forever uses the output of the command ps somewhere in order to determine which processes are candidate for killing. So I moved the ps binary inside the chroot environment and bingo :) The issue was solved.
