### ISSUE TITLE
Regression in 0.13.0: `killed by signal` no longer logged

### ISSUE THREAD

**Issue by triccardi-systran** [foreverjs/forever#645]
Commit 8e4f1fbebda7bf5495f6b4f90b85118cfe657952 introduced a regression: when 'exit:code' event has `code === null`, then it logs `Forever detected script exited with code: null`, whereas it previously logged `Forever detected script was killed by signal: ...`.

The real test should probably be `!(code === undefined || code === null)`.

**Comment by indexzero** [comment]
This is fixed.
