### ISSUE TITLE
watch ignore several sub directories

### ISSUE THREAD

**Issue by grants** [foreverjs/forever#648]
forever --watchIgnore can't ignore multiple sub directories under the --watchDirectory, can it be fixed?

**Comment by indexzero** [comment]
@grants you want a `.foreverignore` file in your watch directory. e.g.:

```
forever start whatever.js --watchDirectory $PWD
```

**$PWD/.foreverignore
```
subdir1/
subdir2/
subdir3
```

**Comment by indexzero** [comment]
Remark: the above is equivalent to:

```
forever start whatever.js --watchIgnore subdir1 --watchIgnore subdir2 --watchIgnore subdir3
```
