### ISSUE TITLE
Is forever compatible with pass phrases?

### ISSUE THREAD

**Issue by danifr** [foreverjs/forever#652]

**Comment by danifr** [comment]
Sorry, I should have explained this better.

I have a XenOrchestra server. I want to start the process using forever (info https://github.com/vatesfr/xo/blob/master/doc/installation/manual_installation.md#misc). I configured my xo to use https/ssl with a pass phrase and it works fine if I start it manually.

My question is: Is there a way to start a server that uses a pass phrase using forever?
Thanks so much,
Dani.

**Comment by danifr** [comment]
Nothing?

**Comment by indexzero** [comment]
@danifr any parameters can be passed to the child process after the script portion of the command. e.g.:

```
forever start my-script.js --any argument --to my --script "dotjs"
```
