### ISSUE TITLE
.foreverignore

### ISSUE THREAD

**Issue by Snorlock** [foreverjs/forever#663]
There doesnt exists alot of documentation on this.
Where can i find this?

**Comment by NawarA** [comment]
I got it working. Add .foreverignore in the directory you're watching, then add

\*\*.log\*\* 

to the file, or whatever file pattern you'd like to ignore. Thats it. I'm using this now

**Comment by indexzero** [comment]
Duplicate of #590. A pull-request for this would be very welcome. It just follows standard ignore syntax like `.gitignore` or `.npmignore`.

**Comment by mikeatlas** [comment]
Is it really necessary to ask for documentation PRs from others for this small feature?

**Comment by ilanbiala** [comment]
Not really sure why @indexzero can't do the docs...if it's so simple then someone who maintains the package really should have written the initial docs as a template for contributors.

**Comment by indexzero** [comment]
PRs welcome to documenation
