### ISSUE TITLE
Official forever repo

### ISSUE THREAD

**Issue by ilanbiala** [foreverjs/forever#666]
Which forever repos should I follow, the ones in this org. or the ones under Nodejitsu?

**Comment by indexzero** [comment]
There are no longer forever repos under Nodejitsu. see: https://github.com/nodejitsu/forever redirects to this repo.

**Comment by ilanbiala** [comment]
@indexzero ah okay, didn't notice the redirect. Why the organization change?

**Comment by indexzero** [comment]
Was easier to manage teams this way.
