### ISSUE TITLE
Closing connections when executing restart

### ISSUE THREAD

**Issue by lght** [foreverjs/forever#669]
Hi,

I've been trying to find a way to close my connections when I restart my express server with `forever restart`.

```
function cleanup() {
  console.log("Closing server ...");
  server.shutdown(); // server is a wrapper for the express server
  process.exit();
}
process.on("SIGINT", cleanup);
process.on("SIGTERM", cleanup);
```

But the `cleanup` function is never called. Is there any way to make it work like that ? I need to call the `server.shutdown` to perform asynchronous tasks.

**Comment by kaven276** [comment]
because forever kill script process with SIGKILL by default

 --killSignal     Support exit signal customization (default is SIGKILL)
help:                       used for restarting script gracefully e.g. --killSignal=SIGTERM
