### ISSUE TITLE
Forever.restart, .restartAll methods

### ISSUE THREAD

**Issue by ilanbiala** [foreverjs/forever#670]
Programmatic restart/restartAll would be nice. It doesn't seem to exist based on the current README.

**Comment by ilanbiala** [comment]
Any info on this?

**Comment by ilanbiala** [comment]
@indexzero is this doable?

**Comment by indexzero** [comment]
Yup, and already implemented :smile: https://github.com/foreverjs/forever/blob/master/lib/forever.js#L560-L567

**Comment by ilanbiala** [comment]
It should probably be added to the README.md then.
