### ISSUE TITLE
--spinSleepTime not working

### ISSUE THREAD

**Issue by youngminz** [foreverjs/forever#671]
I'm using python with forever. Because of syntax error, I determined to use forever. Syntax error raises exception in minute time. so I set --minUptime to 1.

```
$ forever start --minUptime 1 --spinSleepTime 500 -l /path/to/python.log -c python test.py
info:    Forever processing file: test.py
```

--minUptime is work well, however, --spinSleepTime does not work. This is log just ran 10 seconds. 

```
$ l | grep python.log
-rw-r--r-- 1 youngmin users  53K Jan 26 14:26 python.log
```

In log, 500 errors were happened. I want to reduce log file!

**Comment by d-bro** [comment]
The parameter does not seem to do very much if I look at this page:

https://github.com/foreverjs/forever/search?utf8=%E2%9C%93&q=spinSleepTime

**Comment by youngminz** [comment]
Oh.. I think it's NOT implemented yet, too.

**Comment by indexzero** [comment]
@d-bro you neglected to search the dependencies used by `forever`: https://github.com/foreverjs/forever-monitor/search?utf8=%E2%9C%93&q=spinSleepTime

**Comment by d-bro** [comment]
Ah, good to know. Please ignore my previous comment.
