### ISSUE TITLE
socket hang up-ECONNRESET

### ISSUE THREAD

**Issue by manV** [foreverjs/forever#691]
I have a hapi server running using forever and on the same machine I am sending requests to that server using node script using request liberary. I am getting socket hangup ECONNRESET error pretty frequently but if I don't use forever then it is working just fine.

**Comment by indexzero** [comment]
@manV this is likely a problem with your app and not with `forever`. Hard to tell without more information, so I'm going to close this now. 

Feel free to post more for us to help you out on this.
