### ISSUE TITLE
Logging into file stops the process

### ISSUE THREAD

**Issue by bojanbass** [foreverjs/forever#692]
Hi,

I'm running some nodejs apps in production with forever and till now it was working without any problems. In the last version I added some additional info logging (through WInston lib) into console, and  forever saved this console output into file, because the app was started as:
forever start --pidFile $pidFile -l $logFile -a -d $nodeApp

before that, I only logged errors into console, so there was not so much data, but now I log also all repsonses from some other services, which can be quite long. 

What happened now is that forever process just crashes in some short time after starting, from 1s to 10s. Looks like it crashes when it's trying to log into file, because logs are just cut in the middle. No other exception is thrown. So the only thing that I think of what could be wrong is that there is some long string writing into file or maybe some special characters, that stops the process.

I use forever version 0.10.11. Maybe there was a bug and it's fixed already? The bad thing is that it's very hard to reproduce the bug, because looks like it just crashes for some of the responses. If there's any idea why this happens, I would appreciate if you could tell me the solution.

Subquestion: is there any way that I can customize logging of forever into file, like to add a timestamp?

Thank you!

**Comment by beyondmore** [comment]
I may have met this problem. May your disk that saves log files is full, so that you can't create a new log file. You can use command 'forever  list' to list your history log files.And use command 'forever cleanlogs'.

**Comment by bojanbass** [comment]
No, it's not possible, disk is 50% free. I also deleted all logs every time before running the process.

**Comment by beyondmore** [comment]
We may haven't met the same problem .but, Which directory your forever log files in ? May you should use command ' df -h ' to check all disk .

**Comment by indexzero** [comment]
Can you please update to `forever@0.15.2` and try again?
