### ISSUE TITLE
"forever" and other monitoring/restarting solutions

### ISSUE THREAD

**Issue by ezeeetm** [foreverjs/forever#695]
Hello all.  We have a test instance of Uptime, installed and running as expected.  However, it fatally excepts very often.  To be fair, this is usually when we are hitting it with unthrottled API calls to add/update checks.

We installed "forever" (https://github.com/foreverjs/forever) , which seems to be a preferred way too restart node.js apps when they fail.  However, even this method is failing sometimes as well (although not nearly as often)

What are others doing to sort of daemonize Uptime and restart it when it fails?

Thanks.

**Comment by indexzero** [comment]
This would be better suited as a StackOverflow question.
