### ISSUE TITLE
[question] Display the generated log file directly in the terminal

### ISSUE THREAD

**Issue by flashios09** [foreverjs/forever#714]
Hi,
Thanks for this node package :+1: 
Sorry for my bad english :(
Before when i start my script using node ```node myScript.js``` i have a **live output** directly on my terminal window, now with forever ```forever start myScript.js``` i have to open the log File(eg.: **/Users/me/.forever/4PwD.log**) and refresh it manually everytime.

How can i display the output of myScript.js **directly in the terminal** ?

Thanks

**Comment by bojidar-bg** [comment]
From the readme:
    -f, --fifo       Stream logs to stdout
so using `forever start script.js -f ` should work..

**Comment by indexzero** [comment]
@flashios09 you can also try dropping the `start` keyword which will make the monitor run in the cli process without daemonizing:

```
forever myScript.js
```
