### ISSUE TITLE
--colors don't work

### ISSUE THREAD

**Issue by dragonbanshee** [foreverjs/forever#718]
Hi, I'm trying to make the logs show color, but the --colors flag doesn't do anything. Here's my input:

`forever -w index.js --colors`

I've tried moving the --colors other places, but the colors have never showed up.

**Comment by dragonbanshee** [comment]
Update: `forever --color` actually gives me colors. Might want to look into this.

**Comment by aleclarson** [comment]
When using `forever --colors --fifo [script]`, I'm also getting no color. I tried `--color` too (didn't work).
