### ISSUE TITLE
Error: Forever detected script excited with code: 0

### ISSUE THREAD

**Issue by leecollings** [foreverjs/forever#725]
I run `sudo forever-service install -s mqtt.js sky-plus-hd-mqtt` and that returns:

forever-service version 0.5.1

Platform - Raspbian GNU/Linux 7 (wheezy)
update-rc.d: using dependency based boot sequencing
sky-plus-hd-mqtt provisioned successfully

But then when I try to set up as a service by using `sudo service sky-plus-hd-mqtt start` or any of the commands (stop, delete, status) I just get a loop of `error: forever detected script exited with code: 0`.

Forever: 0.14.2
Node: 0.12.1

Can anyone help me understand what the error code means, and what's going wrong?

**Comment by indexzero** [comment]
`forever-service` has not existed for over a year.

**Comment by leecollings** [comment]
Um, excuse me but it's here - https://github.com/zapty/forever-service and the author has even been trying to help me in the last few weeks.

Closing my issue isn't a solution, or any form or help at all, so I'd kindly appreciate you re-open it until I feel that my issue has been resolved.

Believe me, forever-service still exists, or else it wouldn't be able to install on my Pi, would it?

At the very least, offer some help maybe?

**Comment by indexzero** [comment]
I didn't write `forever-service`. Not familiar with it. Sorry I can't be more helpful. I would suggest opening an issue on that repository.

**Comment by leecollings** [comment]
I did, and the author of that suggested I created the issue on your
repository... Could you maybe introduce another service that would be able
to do what I want? What does the forever-monitor one do?

Regards,

*Lee*

**Comment by indexzero** [comment]
This feels like a bug in `mqtt.js sky-plus-hd-mqtt`. Your process is gracefully exiting. That is it is exiting with an exit code of `0`. So from the perspective of `forever` it is attempting to restart it. Again, sorry I can't be more helpful.

**Comment by leecollings** [comment]
I you were to see my sky-plus-hd-mqtt script, do you think you might be
able to identify what the bug or problem might be?

Regards,

*Lee*
