### ISSUE TITLE
Babel?

### ISSUE THREAD

**Issue by tkambler** [foreverjs/forever#735]
@indexzero - Working on that PR we discussed yesterday (JSON config files containing arrays). What are your thoughts on integrating Babel? Would you consider a PR that used it?

**Comment by indexzero** [comment]
I'm not opposed to it, but there are more important things to put your energy into if you've got time: https://github.com/foreverjs/forever/issues/624. The non-breaking internal changes are the most interesting to me. Especially using [nash](https://github.com/scottcorgan/nash)
