### ISSUE TITLE
`--id` is not documented

### ISSUE THREAD

**Issue by dominykas** [foreverjs/forever#742]
Introduced in https://github.com/foreverjs/forever/pull/471, `--id` is not documented.

It is also a little bit confusing next to `--uid` (which seems to have originally been invented to solve the same problem, but started doing a different thing). `--uid` is also documented tautologically: `--uid            Process uid` and it should not be used `as a namespace for processes`, I believe, because it seems that `u` stands for "unique" (i.e. it's used for the default pid file name - which means you shouldn't really have multilple processes with the same `uid`, whereas `id` is OK for that, if I'm not mistaken).

It also seems to me that `--id` would better be called `--title` or `--name` - there also seem to be issues with similar problems to #461 suggesting these names as a solution the same problem, but I'm not sure what's the policy of renaming CLI args here :)

**Comment by mik01aj** [comment]
+1, this is confusing.

Also looks related to my issue https://github.com/foreverjs/forever/issues/722

**Comment by James1x0** [comment]
+1 --id doesn't actually work for me and I need a reliable way to restart processes automatically.

**Comment by dominykas** [comment]
stalebot-ing myself.
