### ISSUE TITLE
workingDir is not respected on multi-app configs

### ISSUE THREAD

**Issue by giratikanon** [foreverjs/forever#743]
Setting `workingDir` in a multi-app config doesn't work, because `spawnWith` only looks for the main thread's `workingDir`: [cli.js#L280](https://github.com/foreverjs/forever/blob/master/lib/forever/cli.js#L280). Each config's `workingDir` is merged into options, but `spawnWith` never gets changed.

So if you're in `/home` and run `forever apps.json`, and `app.json` looks like this:

```
[
  {
    ...
    "workingDir": "/app-1" 
  }, 
 {
    ...
    "workingDir": "/app-2" 
  }
]
```
But `process.cwd()` for `app-1` and `app-2` returns this:

```
/home
```

**Comment by indexzero** [comment]
This was fixed in `0.15.2`
