### ISSUE TITLE
First hit to server is really slow

### ISSUE THREAD

**Issue by vko-online** [foreverjs/forever#759]
I'm just running my nodejs app like this,
`forever start server.js`, but whenever i hit my server, first response is slow. Always, when i stop requesting server for a while and after 4-10min again request data, first response again slow. Waiting 10-40 seconds.
What can it be?

Also noted some options, like `--minUptime`, `--spinSleepTime` but not sure should i use them or not.

**Comment by indexzero** [comment]
This is most likely not related to `forever`. I would suggest opening a question on StackOverflow with implementation details of your Node.js application.
