### ISSUE TITLE
forever doesn't works for sails

### ISSUE THREAD

**Issue by pulkitnandan** [foreverjs/forever#761]
I'm trying to follow dev doc's regarding deployment and trying to lift my app's production version live forever on port 80, but it stay where it was and nothing procceds further. Have a look at its follow up on

https://github.com/balderdashy/sails/issues/3220

**Comment by indexzero** [comment]
@mikermcneil I don't feel like this is related to `forever`. Can you help @pulkitnandan?

**Comment by pulkitnandan** [comment]
Please let me know why it 's not. 

until myserver; do
    echo "Server 'myserver' crashed with exit code $?.  Respawning.." >&2
    sleep 1
done

![image](https://cloud.githubusercontent.com/assets/5687927/9979916/10dab49a-5fa2-11e5-9ba8-ecca9d011be6.png)

**Comment by indexzero** [comment]
It is because you are running `sudo forever start` and then `forever list`. Run `sudo forever list`.
