### ISSUE TITLE
Use forever to run scripts overnight

### ISSUE THREAD

**Issue by acegreen** [foreverjs/forever#762]
Hi

I'm interested in scheduling a script to run every ingot at a specific time and stop when it's done executing until the next day.

I was wondering if forever can be used for that. I understand that forever was not designed for that but there is a reason behind my question. I already use forever to run another script FOREVER (no pun intended) so it would be ideal to not have to install anything else and just use forever for scheduled script run

Thanks in advance

**Comment by indexzero** [comment]
This is not the purpose of forever. I suggest using cron
