### ISSUE TITLE
--killSignal ignored by forever

### ISSUE THREAD

**Issue by alex7egli** [foreverjs/forever#764]
I am using the --killSignal flag when calling stop with forever but the SIGKILL command is still being used. This is the stop command I use:
forever --killSignal=SIGTERM stop index.js

In my code I bound a listener to SIGTERM and SIGINT and neither are called. I also see in the logs:
error: Forever detected script was killed by signal: SIGKILL

**Comment by egirshov** [comment]
I believe the `killSignal` option should be given in the `forever start` command

**Comment by alex7egli** [comment]
Thanks, that was correct. I used:
forever --killSignal=SIGTERM start index.js

And when I run 'forever stop index.js' I see in the log:
error: Forever detected script exited with code: 143
