### ISSUE TITLE
"forever command not found" in spite of installed globally

### ISSUE THREAD

**Issue by raisonde** [foreverjs/forever#765]
I did both
npm install -g forever
and
npm install forever -g

in rood user

I received below

# npm install -g forever
npm WARN optional dep failed, continuing fsevents@1.0.0
/usr/local/nodejs/v0.10.31/bin/forever -> /usr/local/nodejs/v0.10.31/lib/node_modules/forever/bin/forever
forever@0.15.1 /usr/local/nodejs/v0.10.31/lib/node_modules/forever
├── path-is-absolute@1.0.0
├── object-assign@3.0.0
├── colors@0.6.2
├── clone@1.0.2
├── timespan@2.3.0
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── nssocket@0.5.3 (eventemitter2@0.4.14, lazy@1.0.11)
├── shush@1.0.0 (strip-json-comments@0.1.3, caller@0.0.1)
├── cliff@0.1.10 (eyes@0.1.8, colors@1.0.3)
├── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, async@0.2.10, pkginfo@0.3.0)
├── utile@0.2.1 (deep-equal@1.0.1, ncp@0.4.2, async@0.2.10, i@0.3.3, mkdirp@0.5.1, rimraf@2.4.3)
├── nconf@0.6.9 (ini@1.3.4, async@0.2.9, optimist@0.6.0)
├── prettyjson@1.1.3 (colors@1.1.2, minimist@1.2.0)
├── flatiron@0.4.3 (optimist@0.6.0, director@1.2.7, prompt@0.2.14, broadway@0.3.6)
└── forever-monitor@1.6.0 (minimatch@2.0.10, ps-tree@0.0.3, chokidar@1.1.0, broadway@0.3.6)

**Comment by indexzero** [comment]
Looks like it worked. Make sure it's in your `PATH`

**Comment by raisonde** [comment]
Should I add path manually? I confirmed there's no forever's path in my $path, and I know adding path can solve this problem. But I thought path would added automatically when I installed globally.
Am I know wrong?

**Comment by tehg00se** [comment]
thats my nigga

**Comment by NextZeus** [comment]
this issue should not be closed, i met this issue today .  please give us a  official resolution 。

**Comment by harshitparmar** [comment]
Hello everyone. I've a solution on this. You can checkout the article at my [Support Portal](http://support.bhavibiztech.com/index.php?rp=/knowledgebase/18/How-to-fix-forever-command-not-found-on-Linux-VPS-.html). Also if you need more asst. do contact me via email and I'll try my best to help you !

**Comment by Dmdv** [comment]
The same issue. 
Users should not add to the PATH manually.
It's not usable at all on remote server.
