### ISSUE TITLE
Please update the npm repository

### ISSUE THREAD

**Issue by LMS007** [foreverjs/forever#781]
npm install forever --save

package.json

...
"forever": "^0.14.2",
...

problem 1

npm -v forever
2.14.2    <------- what??

problem 2

first line of CHANGELOG.md

v0.13.0 / Tue, 4 Nov 2014
=========================

This is really confusing

**Comment by philipbordallo** [comment]
Try `npm view forever version`, as `npm -v forever` will just give you the version of **npm** you have installed.

**Comment by ultimate-tester** [comment]
This issue should be closed.

`npm view forever version`

returns version 0.15.1 which is the latest.
