### ISSUE TITLE
npm WARN optional dep failed, continuing fsevents@1.0.6

### ISSUE THREAD

**Issue by ailjiuai** [foreverjs/forever#788]
![2015-12-28 6 09 05](https://cloud.githubusercontent.com/assets/8022424/12017144/2329ee2e-ad8e-11e5-8760-ed6687b55983.png)
Excuse me,how can I solve this ？

**Comment by AamuLumi** [comment]
Hi !

The problem come from npm (the issue detailled [here](https://github.com/npm/npm/issues/10768)).
A solution is to downgrade your npm version to v3.3.12.

`npm install -g npm@3.3.12`

**Comment by indexzero** [comment]
Thanks for the help @AamuLumi. Marking this as resolved.

**Comment by sunfeng90** [comment]
I have this problem.

**Comment by sunfeng90** [comment]
I have this problem.

**Comment by hybridappdev** [comment]
I have downgrade node@3.3.12 but still facing the problem. i am tring to run Zero to hero with reactJS

**Comment by radavel** [comment]
@AamuLumi I used your code `npm install -g npm@3.3.12` and now i can't use npm command.

**Comment by kadzany** [comment]
Thanks! this solved my issue.
