### ISSUE TITLE
Forever 0.5.1 with GlusterFS

### ISSUE THREAD

**Issue by auzty** [foreverjs/forever#794]
Hello, my infrastructure need using glusterfs, and distributing my nodejs code, but since using forever v0.5.1 if i edit the file from other server, the forever didn't restart it,
so i still using v0.14.1 , and it's works, maybe some bugs or issue with v0.5.1 ? or this is a feature reduction ? thanks you

**Comment by indexzero** [comment]
forever@0.5.1 is no longer supported officially.
