### ISSUE TITLE
Does forever support binary executable monitoring?  

### ISSUE THREAD

**Issue by bhaveshgohel** [foreverjs/forever#800]
Does forever support binary executable monitoring?
If yes, then how to monitor compiled c file executable. since it don't need "COMMAND to execute" as suggested in options.

```
 -c  COMMAND      COMMAND to execute (defaults to node)
```

Thanks.
-Bhavesh

**Comment by bhaveshgohel** [comment]
Just for reference i'm running below command:

```
$ forever start -o ./logs/out.log -e ./logs/err.log  ./main
```
Here is the Error:
```
(function (exports, require, module, __filename, __dirname) { ⌂ELF☺☺☺
                                                              ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
error: Forever detected script exited with code: 1
```

I m aware that process was run with node as default. I've also tried with the arg '-c "" ', but it's also failing like before :
```
$ forever start -o ./logs/out.log -e ./logs/err.log -c ""  ./main
```

**Comment by indexzero** [comment]
@bhaveshgohel need more information. What version of node, npm, and forever are you running?

**Comment by bhaveshgohel** [comment]
forever: 0.15.1
Nodejs: 4.2.4
OS: DietPi v105 [Debian Jessie]
Hardware: Raspberry Pi 1 B+ 512MB

Am i missing anything in Command?
```bash
$ forever start -o ./logs/out.log -e ./logs/err.log  ./main
```

Here "main" is the compiled c executable.


Test C Code you can try:
```c
int main(int argc, char const *argv[])
{
    printf("Hello World\n");
    return 0;
}
```

**Comment by indexzero** [comment]
@bhaveshgohel yes you are. You syntax for `-c` is slightly off. `-c "" ./main` should be `-c ./main`. The full command would be:

```
$ forever start -o ./logs/out.log -e ./logs/err.log  -c ./main
```

**Comment by bhaveshgohel** [comment]
@indexzero :

Sorry but that was incorrect command. [leading to help]
```
$ forever start -o ./logs/out.log -e ./logs/err.log  -c ./main
```

Corrected:
```
$ forever start -o ./logs/out.log -e ./logs/err.log  ./main -c
```

But Still getting the same error:

```
(function (exports, require, module, __filename, __dirname) { ⌂ELF☺☺☺
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
error: Forever detected script exited with code: 1
```
Above error thrown when its not an node.js file. [http://stackoverflow.com/questions/25322061/what-is-elf-something-line-feed]

Here it's compiled c executable(Binary) and not an nodejs script.
My code is running smoothly without forever. so that is also not an issue. 

Can we fix it?

Please, If anything is unclear, let me know. :)

**Comment by vgatto** [comment]
One work-around is to wrap your binary in a simple shell script that just runs main.

`forever start -o ./logs/out.log -e ./logs/err.log  -c /bin/bash run-main.sh`

**Comment by sunfeng90** [comment]
When I run forever start iotgo,I got this error as following:
(function (exports, require, module, __filename, __dirname) { # !/bin/bash

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm: 2.15

node:4.4.2

forever:0.15.1
