### ISSUE TITLE
Forever process quits without obvious reason and doesn't restart.

### ISSUE THREAD

**Issue by MichMich** [foreverjs/forever#801]
Hi Guys,

I could really use some help, cause I'm pulling my hair ... I created a small node.js script that I start with forever. Unfortunately, this script stops running every few days without any errors (noting odd in my logs), and doesn't restart. 

I've got 3 other node.js scripts running for over 100 days now, so forever does it's job perfect these scripts (it even restarts when the scripts fail.) Unfortunately I can't seem to figure out why the particular script stops, and why it doesn't restart. Is there a good way to debug this?

Thanks in advance!

**Comment by marksoper** [comment]
I can try to help with a 2nd set of eyes. A good place to start, perhaps you've already thought of this, is whether there are any differences in how you're using forever in the failure case - e.g. what command-line options.

**Comment by MichMich** [comment]
I just tried starting it with the -e flag to log any errors. If the script fails again, I'll report back on the results. Any other flags I could try?
