### ISSUE TITLE
Logs are being truncated

### ISSUE THREAD

**Issue by nriesco** [foreverjs/forever#831]
As described in this post [http://stackoverflow.com/questions/36490876/forever-is-truncating-logs/36529957#36529957](http://stackoverflow.com/questions/36490876/forever-is-truncating-logs/36529957#36529957) my logs get truncated.

I use the default options: `forever start /path/to/app.js` and every 4-8 hours the current log starts from 0. The log wasn't getting too big at all, it varies form 80-120 megs aprox and previously I had much bigger logs (1.3Gigs +) with no problems.

This approach works [http://stackoverflow.com/a/36529957/2027670](http://stackoverflow.com/a/36529957/2027670) but it makes app administration too complex.

Log rotation is not even an issue since logs are truncated before I can event think of rotating something.

Versions in use:
- node v0.12.7
- npm 2.11.3
- forever v0.15.1
- 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

The server has plenty of storage available (10-15 gigs at least)

**Comment by ultimate-tester** [comment]
I don't think this bug is related to forever. Forever uses the module Winston to log it's stuff.
Winston handles the rest, I think Winston is truncating your log files. I will inspect the Winston source code for you to see if I can find anything that explains why the logs are getting truncated. Did you find out any pattern in this behavior?

**Comment by nriesco** [comment]
@ultimate-tester The files were ok: [http://stackoverflow.com/questions/36490876/forever-is-truncating-logs](http://stackoverflow.com/questions/36490876/forever-is-truncating-logs)

 The problem had nothing to do with forever, nor winston. I didn't realise that the files were so big that the log viewer was only showing part of it. The confusing part is that the first line (past) was truncated by the viewer (OSX Console) what led me to think that the file itself was truncated.
