### ISSUE TITLE
Did development of Forever stop?

### ISSUE THREAD

**Issue by entrptaher** [foreverjs/forever#842]
There were just no update of Forever since last 10 months. 
What happened? NodeJS version out of date, Deps out of date, build failing etc etc.
I use forever and PM2, sometime I use forever and PM2 on same project to cover each others failures. 
But, I wonder, what happened to the development?
:/

**Comment by indexzero** [comment]
The long and the short of it is that I relocated from New York to California and then back to New York in the last year. I'll be focusing on `forever` next Wednesday at the [EmpireJS OSS night](http://2016.empirejs.org/#oss-night). If you're in New York you should come by.

**Comment by entrptaher** [comment]
I think the issue is not solved until forever has no more build failing or deps out of date notice.

**Comment by indexzero** [comment]
Contributions are welcome. I'm sorry if my answer is not to your satisfaction.
