### ISSUE TITLE
Is forever going to be deprecated?

### ISSUE THREAD

**Issue by ChuanyuWang** [foreverjs/forever#855]
I notice that there is only two commits since 2016, is forever going to be deprecated forever?
Is there any alternative tool for this?

**Comment by alfonsomga** [comment]
> Is there any alternative tool for this? 

https://github.com/Unitech/pm2

**Comment by bena-townsquared** [comment]
[pm2 is licensed under the AGPL](https://twitter.com/teabass/status/669564799005650944)

**Comment by adamreisnz** [comment]
Yeah, PR's aren't being merged either. It seems this project is coming to an end.

**Comment by kibertoad** [comment]
Maybe not ;)
