### ISSUE TITLE
 npm WARN deprecated minimatch@2.0.10 (DoS Issue!!!!)

### ISSUE THREAD

**Issue by e-dot** [foreverjs/forever#858]
forever is depending on an obsolete/deprecated version of minimatch. This old version has a security issue, can you please upgrade?

When you install forever, npm displays:
**npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue**

**Comment by alextmeyer** [comment]
This is actually an issue due to an outdated version number of minimatch being in forever-monitor. https://github.com/foreverjs/forever-monitor/blob/master/package.json#L26. Will make an issue against that repo and link this ticket

**Comment by willvlad** [comment]
+1

**Comment by corpr8** [comment]
+1

**Comment by andresmatasuarez** [comment]
+1. `forever-monitor` repo has already been updated to use the right version of minimatch. However, this package still dependes on the old version of `forever-monitor`, which is the `1.6.0` (as opposed to the correct one which is `1.7.0`).

A new version dump is required in this project

**Comment by indexzero** [comment]
Fixed.
