### ISSUE TITLE
How to remove stopped processes from forever list

### ISSUE THREAD

**Issue by yidan621** [foreverjs/forever#863]
<img width="235" alt="screen shot 2016-08-02 at 10 08 24 pm" src="https://cloud.githubusercontent.com/assets/18137871/17331513/db4e51fa-58fd-11e6-955e-fd8255a499c5.png">
Is there a way to remove stopped processes from forever list?

**Comment by yidan621** [comment]
I got it. Simply removing the /home/ec2-user/.forever directory works!

**Comment by dstoyer** [comment]
Removing the .forever directory is not a good solution for removing stopped processes from the forever list.
To remove stopped forever processes from the forever list:
1. Execute forever list.
1. Note the number under the "forever" column in the row of the stopped process, this is the system process id (pid) of the **monitoring process** for the forever process (whether stopped or running).
    + If you don't see a "forever" column in the list, execute the forever command with 'column add  forever':
    `forever column add  forever`
    Then run `forever list` again, you should now see the "forever" column at the end each line.
1. Execute `kill <pid>`, where <pid> is the number noted above.
1. Execute `forever list` again, the stopped process should be gone from the list.

**Note**:
Killing the forever monitor process does not kill the forever process itself, it only kills the process monitoring the actual forever process which removes the row from the listing.

**Comment by luisAzcuaga** [comment]
I was fighting with the same. Typing `forever stop <id>` (NO **PID** nor **forever PID**) this removes the items from the list. Also typing the next command will remove everything: `forever stopall`

If you don't know what's the id you want to stop /remove from the list, check using `forever list`

**Comment by dennishu001** [comment]
I don't know why the previous post was down-voted.  For stopped process <id>,  type `forever stop <id>` will cause forever to complain `cannot find process with id: <id>`, nevertheless, the stopped process WILL be removed from the list.
