### ISSUE TITLE
Logfile parameters ignored?

### ISSUE THREAD

**Issue by flyon** [foreverjs/forever#868]
Whatever I do, forever seems to ignore my log parameters and creates its own logfile.

start_node_server.sh:
    
    cd /opt/nodejs/
    forever start dist/init.js -o nodejs_out.log -e nodejs_err.log -l nodejs_forever.log -a`
    
I run `start_node_server.sh` as root, but the logfiles are not created.
`forever logs` returns 

    info:    Logs for running Forever processes
    data:        script       logfile
    data:    [0] dist/init.js /root/.forever/z8Nd.log

I changed the path of the logfiles to just a filename, made sure folders are writable... what am I doing wrong?

**Comment by giannicic** [comment]
I think it's
`forever -o nodejs_out.log -e nodejs_err.log -l nodejs_forever.log -a start dist/init.js `

**Comment by adambuczynski** [comment]
How to specify the logfile parameters in a JSON configuration file?

**Comment by adambuczynski** [comment]
To answer my own question, apparently those are errFile, logFile and outFile, as can be deduced from here: https://github.com/foreverjs/forever/blob/master/lib/forever/cli.js#L110-L126

This should probably be documented in the readme though. I'll create a PR.

**Comment by flyon** [comment]
`forever -o nodejs_out.log -e nodejs_err.log -l nodejs_forever.log -a start dist/init.js`

that worked, tnx
