### ISSUE TITLE
minUptime and spinSleepTime warnings even if passed as parameter or in config file

### ISSUE THREAD

**Issue by adamreisnz** [foreverjs/forever#870]
Whether specified via config:

```
{
  "path": "./",
  "script": "app/index.js",
  "minUptime": 1000,
  "spinSleepTime": 10000,
  "args": [
    "--env", "production"
  ]
}

```

Or via command line:

```
> forever start ./forever.json --minUptime 1000 --spinSleepTime 10000
```

I keep getting these warnings:

```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
```

Also, minUptime should probably be called `minUpTime` with a capital T for consistency.

**Comment by ChristopherNeuwirth** [comment]
+1

**Comment by adamreisnz** [comment]
Is this ever going to get fixed? :(

**Comment by adamreisnz** [comment]
Never mind, I've switched to pm2 instead, which still seems to be actively maintained.

**Comment by Saiprasad02** [comment]
-- minUptime not set. Defaulting to: 1000ms 

Is any body solve this issue? if any body have a solution please inform here.

**Comment by adamreisnz** [comment]
The solution is to switch to [pm2](https://www.npmjs.com/package/pm2), which is an actively maintained package unlike this one.

**Comment by BilalHadid** [comment]
forever start --minUptime 100000 --spinSleepTime 10000 server.js
