### ISSUE TITLE
run forever on re-boot

### ISSUE THREAD

**Issue by raspman** [foreverjs/forever#951]
Hi,

Have forever running server.js just fine, but I have no figured out how to get it to automatically run should the raspberry pi re-boot.  I think the main issue is the path I am provide in the various scripts I've used is not correct.  If someone can walk me through the process of identifying the exact path I need and how to set up, I'd really appreciate it..

**Comment by Tilogorn** [comment]
Do you still need help? The file /etc/rc.local gets executed at boot, so just enter your forever call there.

```
$ sudo nano /etc/rc.local
```

``` //etc/rc.local
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

forever --workingDir [abs.path]/[folder] start [abs.path]/[folder]/server.js
exit 0
```
Example: 
```
forever --workingDir /projects/my-node-project start /projects/my-node-project/server.js
```

I had to add the `--workingDir` option so that all my paths defined in server.js were still correct.

**Comment by raspman** [comment]
Thanks...I was able to figure it out...appreciate the response, however.
